import React, { useState } from 'react';
import { Sparkles, Send, Copy, RefreshCw } from 'lucide-react';
import { AIReport } from '../../types';

interface ReportGeneratorProps {
  projectId: string;
  onGenerate: (report: AIReport) => void;
}

const ReportGenerator: React.FC<ReportGeneratorProps> = ({ projectId, onGenerate }) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [report, setReport] = useState<AIReport | null>(null);
  const [showPreview, setShowPreview] = useState(false);

  const generateReport = async () => {
    setIsGenerating(true);
    
    // Simulate AI generation delay
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    // Generate mock AI report
    const mockReport: AIReport = {
      id: `REP-${Date.now()}`,
      projectId,
      summary: "The Brand Redesign Project has made significant progress this week with the completion of the logo concepts phase. Client feedback has been positive, and we're on track to meet the March 30th deadline. The team has shown excellent collaboration and creativity throughout the process.",
      actions: [
        "Present final logo concepts to client stakeholder meeting on Friday",
        "Begin development of brand guidelines document incorporating approved design elements",
        "Schedule user testing sessions for the new brand identity with target audience"
      ],
      risk: "Potential delay risk identified in brand guidelines phase due to client's expanded scope requirements. Recommend scheduling alignment call to clarify deliverables and timeline expectations.",
      generatedAt: new Date(),
      recipients: []
    };
    
    setReport(mockReport);
    setShowPreview(true);
    setIsGenerating(false);
  };

  const sendReport = () => {
    if (report) {
      onGenerate({
        ...report,
        sentAt: new Date(),
        recipients: ['client@example.com', 'pm@example.com']
      });
      setShowPreview(false);
      setReport(null);
    }
  };

  const copyReport = () => {
    if (report) {
      const reportText = `
Weekly Project Report - ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY:
${report.summary}

KEY ACTIONS:
${report.actions.map((action, index) => `${index + 1}. ${action}`).join('\n')}

RISK ASSESSMENT:
${report.risk}

Generated by NexaFlow AI on ${report.generatedAt.toLocaleString()}
      `.trim();
      
      navigator.clipboard.writeText(reportText);
    }
  };

  return (
    <div className="bg-white rounded-xl border border-gray-200 p-6">
      <div className="flex items-center space-x-3 mb-6">
        <div className="p-2 bg-purple-100 rounded-lg">
          <Sparkles className="w-6 h-6 text-purple-600" />
        </div>
        <div>
          <h3 className="text-lg font-semibold text-gray-900">AI Weekly Report</h3>
          <p className="text-sm text-gray-600">Generate intelligent project summaries and insights</p>
        </div>
      </div>

      {!showPreview ? (
        <div className="space-y-4">
          <div className="bg-gradient-to-r from-purple-50 to-blue-50 rounded-lg p-6 border border-purple-200">
            <h4 className="font-medium text-gray-900 mb-2">What gets included:</h4>
            <ul className="text-sm text-gray-600 space-y-1">
              <li>• 3-sentence executive summary of project progress</li>
              <li>• 3 key actions and next steps for the team</li>
              <li>• 1 critical risk assessment and mitigation</li>
              <li>• Activity analysis from the past week</li>
            </ul>
          </div>

          <button
            onClick={generateReport}
            disabled={isGenerating}
            className="w-full flex items-center justify-center space-x-2 px-6 py-3 bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-lg hover:from-purple-700 hover:to-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isGenerating ? (
              <>
                <RefreshCw className="w-5 h-5 animate-spin" />
                <span>Analyzing project data...</span>
              </>
            ) : (
              <>
                <Sparkles className="w-5 h-5" />
                <span>Generate Weekly Report</span>
              </>
            )}
          </button>
        </div>
      ) : (
        <div className="space-y-6">
          <div className="bg-gray-50 rounded-lg p-6">
            <div className="flex items-center justify-between mb-4">
              <h4 className="font-semibold text-gray-900">Generated Report Preview</h4>
              <button
                onClick={copyReport}
                className="flex items-center space-x-1 text-sm text-gray-600 hover:text-gray-800"
              >
                <Copy className="w-4 h-4" />
                <span>Copy</span>
              </button>
            </div>

            <div className="space-y-4">
              <div>
                <h5 className="font-medium text-gray-900 mb-2">Executive Summary</h5>
                <p className="text-gray-700 leading-relaxed">{report?.summary}</p>
              </div>

              <div>
                <h5 className="font-medium text-gray-900 mb-2">Key Actions (3)</h5>
                <ul className="space-y-2">
                  {report?.actions.map((action, index) => (
                    <li key={index} className="flex items-start space-x-2">
                      <span className="flex-shrink-0 w-6 h-6 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-sm font-medium">
                        {index + 1}
                      </span>
                      <span className="text-gray-700">{action}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div>
                <h5 className="font-medium text-gray-900 mb-2">Risk Assessment</h5>
                <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
                  <p className="text-gray-700">{report?.risk}</p>
                </div>
              </div>
            </div>
          </div>

          <div className="flex space-x-3">
            <button
              onClick={generateReport}
              className="flex items-center space-x-2 px-4 py-2 text-gray-600 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
            >
              <RefreshCw className="w-4 h-4" />
              <span>Regenerate</span>
            </button>
            <button
              onClick={sendReport}
              className="flex-1 flex items-center justify-center space-x-2 px-6 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
            >
              <Send className="w-4 h-4" />
              <span>Send Report</span>
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default ReportGenerator;